version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VeryStrongPassword123
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql
      - ./scripts:/usr/src/app/scripts
    container_name: sqlserver
    restart: always

volumes:
  db_data:
